<?php $data = $block->getOrders() ?>
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>-->

<table class="table table-striped">

    <thead>
    <tr>
        <th>Order iD</th>
        <th>Rule Id</th>
        <th>Rule name</th>
        <th>Discount</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ( $data as $item ): ?>
        <tr>
            <td><?php echo $item['order_id'] ?></td>
            <td><?php echo $item['rule_id'] ?></td>
            <td><?php echo $item['name'] ?></td>
            <td><?php echo $item['discount_amount'] ?> %</td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>
<div class="maindiv">
    <div class="secondary">

    </div>
</div>
<div >
    <button data-mage-init='{"test_Js":{"someKey": "value"}}'>Test Js</button>
</div>
<div id="popup-modal" style="display:none;">
    <h1> This is test  </h1>
</div>
<div>
<!--    <script type="text/x-magento-init">-->
<!--    {-->
<!--        ".maindiv": {-->
<!--            "myCustomWidget": {-->
<!--                "passvalue": "custom message",-->
<!--                "abcd": 123-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--    </script>-->
